name = "Perseus S2"
author = "sans9536, minecraftbossdj"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80efbd00dcbd61f97660414eda17e888e6874859243de85a172043c12f8b016c"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
