name = "Perseus S2"
author = "sans9536, minecraftbossdj"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79f5e96edfc8cc27fde1ea35fae23663f8510894cee95ff2d92eaf19220e2c62"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
