name = "Perseus S2"
author = "sans9536, minecraftbossdj"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f8d7869db13e846c02368b99be9c5454378bab0f563877fac9376b8fa29d2e2"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
